version: '3.4'

networks:
  mlc_net:
    external:
      name: mlc_net

services:
  db:
    image: mysql:5.7
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - mlc_net

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - '${PMA_PORT}:80'
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_USER: ${DB_USER}
#      PMA_PASSWORD: ${DB_PASSWORD}
#    depends_on:
#      - db
#    networks:
#      - mlc_net

  engine:
    build: .
    ports:
      - '${ENGINE_PORT}:9000'
    volumes:
      - ".:/var/www/Symfony"
      - "./docker/logs:/var/www/Symfony/var/logs/:rw" #retrieve log files
      - "./docker/engine/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    networks:
      - mlc_net

  front:
    image: nginx:latest
    ports:
      - '${FRONT_PORT}:8000'
    volumes:
        - "./docker/logs:/var/log/nginx" #retrieve log files
        - "./docker/front/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./docker/front/moncompte.conf:/etc/nginx/conf.d/moncompte.conf:ro"
        - "./web/:/var/www/Symfony/web"
    restart: always
    networks:
      - mlc_net


#  email-catcher:
#    image: schickling/mailcatcher
#    ports:
#      - '1025:1025'
#      - '1080:1080'
#    networks:
#      - mlc_net
