version: '3.4'

networks:
  cyclos-net:
    driver: bridge
  symfony-net:
    driver: bridge

#volumes:
#  cel-data:
#    name: cel-data

services:
  db:
    image: mysql:5.7
    ports:
      - '${DB_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    networks:
      - symfony-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '${PMA_PORT}:80'
    networks:
      - symfony-net
#    environment:
#      - "PMA_HOST=db"
#      - "PMA_PORT=3306"
#      - 'PMA_USER= root' #${DB_USER}'
#      - 'PMA_PASSWORD=  #${DB_PASSWORD}'
#    depends_on:
#      - db

  engine:
    build: .
    image: mazda/fastcgi
    ports:
      - '${ENGINE_PORT}:9000'
    volumes:
      - ".:/var/www/Symfony"
      - "./docker/logs:/var/www/Symfony/var/logs/:rw" #retrieve log files
      - "./docker/engine/php.ini:/usr/local/etc/php/php.ini"
    restart: always
    networks:
      - symfony-net
      - cyclos-net

  front:
    image: nginx:latest
    ports:
      - '${FRONT_PORT}:8000'
    volumes:
        - "./docker/logs:/var/log/nginx" #retrieve log files
        - "./docker/front/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./docker/front/moncompte.conf:/etc/nginx/conf.d/moncompte.conf:ro"
        - "./web/:/var/www/Symfony/web"
    restart: always
    networks:
      - symfony-net

  cyclos-app:
    image: cyclos/cyclos:4.8.2
    environment:
    - DB_HOST=cyclos-db
    - DB_NAME=cyclos
    - DB_USER=cyclos
    - DB_PASSWORD=cyclos
    restart: always
    ports:
    - '${CYCLOS_PORT}:8080'
    networks:
      - cyclos-net
  cyclos-db:
    image: cyclos/db
    volumes:
      - ./cyclos-dump-minimal.sql:/docker-entrypoint-initdb.d/cyclos-dump-minimal.sql #dump done automatically by postgre
    environment:
    - POSTGRES_DB=cyclos
    - POSTGRES_USER=cyclos
    - POSTGRES_PASSWORD=cyclos
    restart: always
    networks:
      - cyclos-net

  email-catcher:
    image: schickling/mailcatcher    
    ports: 
      - '1025:1025'
      - '1080:1080'
    networks:
      - symfony-net
