version: '3.4'

services:

  engine:
    volumes:
      - ".:/var/www/Symfony"
      - "./docker/logs:/var/www/Symfony/var/logs/:rw" #retrieve log files
      - "./docker/engine/php.ini:/usr/local/etc/php/php.ini"
      - "./docker/engine/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
  front:
    volumes:
        - "./docker/logs:/var/log/nginx" #retrieve log files
        - "./docker/front/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./web/:/var/www/Symfony/web"


  email-catcher:
    image: schickling/mailcatcher
    ports:
      - '1025:1025'
      - '1080:1080'
    networks:
      - mlc_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '${PMA_PORT}:80'
    networks:
      - mlc_net
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: 'root'
      PMA_PASSWORD: '${DB_PASSWORD}'
    depends_on:
      - db

  doc-generator:
    image: phpdoc/phpdoc
    volumes:
      - ".:/var/www/Symfony"
    networks:
      - mlc_net
    depends_on:
      - engine
