version: '3.4'

networks:
  mlc_net:
    external:
      name: mlc_net

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - mlc_net

  engine:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        xdebug_enabled: ${XDEBUG_ENABLED}
        xdebug_remote_host: ${XDEBUG_REMOTE_HOST}
        xdebug_remote_port: 9001
    ports:
      - '${ENGINE_PORT}:9000'
      - '${XDEBUG_REMOTE_PORT}:9001' #XDEBUG
    volumes:
      - "./docker/logs:/var/www/Symfony/var/logs/:rw" #retrieve log files
    environment:
      - XDEBUG_CONFIG="remote_host=${XDEBUG_REMOTE_HOST}"
    networks:
      - mlc_net

  front:
    image: nginx:latest
    ports:
      - '${FRONT_PORT}:8000'
    volumes:
        - "./docker/front/moncompte.conf:/etc/nginx/conf.d/moncompte.conf:ro"
        - "./docker/logs:/var/log/nginx" #retrieve log files
        - "./web/:/var/www/Symfony/web"
    networks:
      - mlc_net

