version: '3.4'

networks:
  cyclos-net:
    driver: bridge
  symfony-net:
    driver: bridge

volumes:
  cel-data:
    name: cel-data

services:
  db:
    image: mysql:5.7
    ports:
      - '3307:3306' #'${DB_PORT}:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=KNicNj3p #${DB_ROOT_PASSWORD}'
      - MYSQL_USER=root #${DB_USER}'
      - MYSQL_PASSWORD=KNicNj3p #${DB_PASSWORD}'
      - MYSQL_DATABASE=symfony_dev #${DB_DATABASE}'
    networks:
      - symfony-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80' #${PMA_PORT}:80'
    networks:
      - symfony-net
#    environment:
#      - "PMA_HOST=db"
#      - "PMA_PORT=3306"
#      - 'PMA_USER= root' #${DB_USER}'
#      - 'PMA_PASSWORD= KNicNj3p' #${DB_PASSWORD}'
#    depends_on:
#      - db

  engine:
    build: .
    image: mazda/fastcgi
    ports:
      - '${ENGINE_PORT}:9000'
    volumes:
      - "cel-data:/var/www/Symfony/var/:rw"
    networks:
      - symfony-net
      - cyclos-net

  front:
    image: nginx:latest
    ports:
      - '${FRONT_PORT}:8000'
    volumes:
        - "cel-data:/var/log/nginx"
        - "./docker/front/nginx.conf:/etc/nginx/nginx.conf:ro"
        - "./docker/front/moncompte.conf:/etc/nginx/conf.d/moncompte.conf:ro"
        - "./web/:/var/www/Symfony/web"
    networks:
      - symfony-net

  cyclos-app:
    image: cyclos/cyclos:4.8.2
    environment:
    - DB_HOST=cyclos-db
    - DB_NAME=cyclos
    - DB_USER=cyclos
    - DB_PASSWORD=cyclos
    # build: ./cyclos
    ports:
    - "1234:8080"
    #    volumes:
    #    - ${PWD}/cyclos/cyclos.properties:/usr/local/cyclos/WEB-INF/classes/cyclos.properties
    networks:
      - cyclos-net
  cyclos-db:
    # build: ./cyclosdb
    image: cyclos/db
    volumes:
      - ./cyclos-dump-minimal.sql:/docker-entrypoint-initdb.d/cyclos-dump-minimal.sql #dump done automatically by postgre
    environment:
    - POSTGRES_DB=cyclos
    - POSTGRES_USER=cyclos
    - POSTGRES_PASSWORD=cyclos
    networks:
      - cyclos-net

