imports:
    - { resource: config_dev.yml }

# No logging on test environment
#monolog:
#    handlers:
#        main:
#            type:   test

security:
    firewalls:
        # replace 'main' by the name of your own firewall
        mobile:
            #looks necessary to allow multiple client requests in a same test action
            #otherwise, client is redirected to authentication point
            stateless: false 

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false
        enabled: true

web_profiler:
    toolbar: true
    intercept_redirects: false

swiftmailer:
    logging: true
    #    disable_delivery: true


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_test_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

dama_doctrine_test:
    enable_static_connection: true
    enable_static_meta_data_cache: true
    enable_static_query_cache: true
