imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: fr

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer:
        enabled: true 
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        gc_maxlifetime: 1500
        cookie_lifetime: 86400
        gc_probability: 1
        gc_divisor: 1
        cookie_httponly: true
        cookie_secure: true
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        card_association_delay: '%card_association_delay%'
        cairn_email_activation_delay: '%cairn_email_activation_delay%'
        security_service: '@cairn_user.security'
        register_url: '%cairn_default_register_url%'
        cgu_url: '%cairn_default_cgu_url%'
        pathToWeb: '%kernel.project_dir%/web'
        signature: '%leading_company%' 
    form_themes:
        - 'form/materialize_form_theme.html.twig'
        - 'form/cairn_form_theme.html.twig'


# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.7
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: '%kernel.project_dir%/src/Migrations'
    # namespace is arbitrary but should be different from App\Migrations
    # as migrations classes should NOT be autoloaded
    namespace: DoctrineMigrations
    table_name: 'migration_versions'
    name: 'Application Migrations'
    # available in version >= 1.2. Possible values: "BY_YEAR", "BY_YEAR_AND_MONTH", false
    organize_migrations: false
        # available in version >= 1.2. Path to your custom migrations template
    custom_template: ~

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    encryption: '%mailer_encryption%'
    spool: { type: memory }

fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Cairn\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%cairn_email_noreply%'
        sender_name: Cairn - noreply
    profile:
        form:
            type: Cairn\UserBundle\Form\ProfileType
    change_password:
        form:
            type: Cairn\UserBundle\Form\ChangePasswordType

    resetting: 
        email:
            template:   CairnUserBundle:Emails:resetting_password_confirmation.email.twig          
    registration:
        form:
            type: Cairn\UserBundle\Form\RegistrationType
        confirmation:
            enabled:    true # change to false to disable registration email confirmation  
            template:   CairnUserBundle:Emails:email_confirmation.email.twig

fos_oauth_server:
    db_driver: orm       
    client_class:        Cairn\UserBundle\Entity\Client
    access_token_class:  Cairn\UserBundle\Entity\AccessToken
    refresh_token_class: Cairn\UserBundle\Entity\RefreshToken
    auth_code_class:     Cairn\UserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username_email
        options:
            access_token_lifetime: '%session_timeout%'


#assetic:
#    debug:          '%kernel.debug%'
#    use_controller: '%kernel.debug%'

knp_snappy:  
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:
            - { name: 'viewport-size', value: ‘1024x768’ }
            - { name: 'page-size', value: 'A4' }
