imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        gc_maxlifetime: 300
        cookie_lifetime: 300
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        card_activation_delay: '%card_activation_delay%'
        cairn_email_activation_delay: '%cairn_email_activation_delay%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        server_version: 5.7
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    port: '%mailer_port%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    Cairn\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: '%cairn_email_noreply%'
        sender_name: Maxime
    profile:
        form:
            type: Cairn\UserBundle\Form\ProfileType

    registration:
        form:
            type: Cairn\UserBundle\Form\RegistrationType
        confirmation:
            enabled:    true # change to false to disable registration email confirmation  
            template:   CairnUserBundle:Emails:email_confirmation.html.twig

fos_oauth_server:
    db_driver: orm       
    client_class:        Cairn\UserBundle\Entity\Client
    access_token_class:  Cairn\UserBundle\Entity\AccessToken
    refresh_token_class: Cairn\UserBundle\Entity\RefreshToken
    auth_code_class:     Cairn\UserBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username

#assetic:
#    debug:          '%kernel.debug%'
#    use_controller: '%kernel.debug%'

knp_snappy:  
    pdf:
        enabled:    true
        binary:     '%kernel.project_dir%/vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
