security:
    encoders:
        Cairn\UserBundle\Entity\User: sha512
        #        Cairn\UserBundle\Entity\User: plaintext

    role_hierarchy:
        ROLE_PERSON: ROLE_ADHERENT
        ROLE_PRO: ROLE_ADHERENT
        ROLE_ADMIN: [ROLE_PRO, ROLE_PERSON]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_PRO' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        main:
            id: fos_user.user_provider.username_email


    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        #        oauth_token: # Everyone can access the access token URL.
        #            pattern: ^/oauth/v2/token
        #            security: false

        api:
            pattern: ^/api
            stateless:  false
            anonymous:  true
            guard:
                authenticators:
                    - 'cairn_user.api_authenticator'


        mobile:
            pattern: ^/mobile
            fos_oauth:  true
            stateless:  true
            anonymous:  true # can be omitted as its default value        

        main:
            pattern:   ^/
            anonymous: true
            json_login:
                check_path: /login
        #                username_path: security.login.username
        #                password_path: security.login.password


            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: cairn_user_welcome
            logout:
                path:       fos_user_security_logout
                target:     fos_user_security_login
            remember_me:
                secret:     '%secret%' #defined in parameters.yml 


    access_control:
        - { path: ^/config, roles: ROLE_SUPER_ADMIN , requires_channel: https, host: moncompte.cairn-monnaie\.com$}
        - { path: ^/api/online-payment/create, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: moncompte.cairn-monnaie\.com$ }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https, host: moncompte.cairn-monnaie\.com$ }
        - { path: ^/config, roles: ROLE_SUPER_ADMIN , requires_channel: http, host: localhost$}
        - { path: ^/api/online-payment/create, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http, host: '%online_payment_hosts%'}
        - { path: ^/api/online-payment/create, roles: ROLE_NO_ACCESS}
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http, host: localhost$ }

