# Cairn/UserBundle/Resources/config/routing.yml

#login:
#    path:     /login
#    defaults: { _controller: CairnUserBundle:Security:login }

cairn_user_welcome:
    path:     / 
    defaults: { _controller: CairnUserBundle:User:index }

cairn_user_install:
    path:     install/
    defaults: { _controller: CairnUserBundle:Default:install }


cairn_user_registration:
    path:     inscription.{_format}
    defaults: { _controller: CairnUserBundle:Default:registration, _format: html }
    requirements:
        _format: html|json

cairn_user_redirect_login:
    path:     login/redirection/{message}/
    defaults: { _controller: CairnUserBundle:Default:redirectToLogin }

cairn_user_password_change:
    path:     password/new/
    defaults: { _controller: CairnUserBundle:User:changePassword }

cairn_user_card_security_layer:
    path:     security/card/
    defaults: { _controller: CairnUserBundle:Card:inputCardKey }

cairn_user_referents_assign:
    path:     user/referents/assign/{id}
    defaults: { _controller: CairnUserBundle:Admin:assignReferent }
    requirements:
        id: \d+

cairn_user_profile_view:
    path:     user/profile/view/{id}.{_format}
    defaults: { _controller: CairnUserBundle:User:viewProfile, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_beneficiaries_list:
    path:     user/beneficiaries/list.{_format}
    defaults: { _controller: CairnUserBundle:User:listBeneficiaries, _format: html }
    requirements:
        _format: html|json

cairn_user_beneficiaries_add:
    path:     user/beneficiaries/add.{_format}
    defaults: { _controller: CairnUserBundle:User:addBeneficiary, _format: html }
    requirements:
        _format: html|json

cairn_user_beneficiaries_edit:
    path:     user/beneficiaries/edit/{id}.{_format}
    defaults: { _controller: CairnUserBundle:User:editBeneficiary, _format: html  }
    requirements:
        id: \d+
        _format: html|json

cairn_user_beneficiaries_remove:
    path:     user/beneficiaries/remove/{id}.{_format}
    defaults: { _controller: CairnUserBundle:User:removeBeneficiary, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_users_home:
    path:     users.{_format}
    defaults: { _controller: CairnUserBundle:User:users, _format: html }
    requirements:
        _format: html|json

cairn_user_email_check_validation:
    path:     user/email/check/expiration/
    defaults: { _controller: CairnUserBundle:Admin:checkEmailsValidation }

cairn_user_users_search:
    path:     user/search/
    defaults: { _controller: CairnUserBundle:User:searchUser }

cairn_user_users_block:
    path:     admin/users/block/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Admin:blockUser, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_users_activate:
    path:     admin/users/activate/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Admin:activateUser, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_users_remove:
    path:     user/remove/{id}.{_format}
    defaults: { _controller: CairnUserBundle:User:confirmRemoveUser, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_card_home:
    path:     card/home/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Card:cardOperations, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_card_check_expiration:
    path:     card/check/expiration/
    defaults: { _controller: CairnUserBundle:Card:checkCardsExpiration }

cairn_user_card_order:
    path:     card/order/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Card:orderCard, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_card_validate:
    path:     card/validate.{_format}
    defaults: { _controller: CairnUserBundle:Card:validateCard, _format: html }
    requirements:
        _format: html|json

cairn_user_card_revoke:
    path:     card/revoke/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Card:revokeCard, _format: html }
    requirements:
        id: \d+
        _format: html|json

#if you change this route's name, change it in EventListener/SecurityListener, in the function "onSensibleOperations"
cairn_user_card_generate:
    path:     card/generate/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Card:generateCard, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_card_download:
    path:     card/download/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Card:downloadCard, _format: html }
    requirements:
        id: \d+
        _format: html|json

cairn_user_banking_rib_download:
    path:     banking/download/rib/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:downloadRIB, _format: html }
    requirements:
        id: "[-]?[0-9]{1,}"
        _format: html|json

cairn_user_banking_transfer_notice_download:
    path:     banking/download/notice/{id}/
    defaults: { _controller: CairnUserBundle:Banking:downloadTransferNotice }
    requirements:
        id: "[-]?[0-9]{1,}"

cairn_user_banking_accounts_overview_download:
    path:     banking/download/accounts/
    defaults: { _controller: CairnUserBundle:Banking:downloadAccountsOverview }

cairn_user_banking_operations:
    path:     banking/operations/{type}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:bankingOperations, _format: html }
    requirements:
        type: transaction|conversion|reconversion|deposit|withdrawal
        _format: html|json

cairn_user_banking_operations_view:
    path:     banking/view/operations/{type}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:viewOperations, _format: html }
    requirements:
        type: transaction|conversion|reconversion|deposit|withdrawal
        _format: html|json

cairn_user_banking_transaction_to:
    path:     banking/transaction/new/to/{frequency}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:transactionTo, _format: html }
    requirements:
        frequency: unique|recurring
        _format: html|json

cairn_user_banking_transaction_request:
    path:     banking/transaction/request/{to}-{frequency}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:transactionRequest, _format: html}
    requirements:
        frequency: unique|recurring
        to: new|beneficiary|self
        _format: html|json

cairn_user_banking_withdrawal_request:
    path:     banking/withdrawal/request.{_format}
    defaults: { _controller: CairnUserBundle:Banking:withdrawalRequest, _format: html }
    requirements:
        _format: html|json

cairn_user_banking_deposit_request:
    path:     banking/deposit/request.{_format}
    defaults: { _controller: CairnUserBundle:Banking:depositRequest, _format: html }
    requirements:
        _format: html|json

cairn_user_banking_reconversion_request:
    path:     banking/reconversion/request.{_format}
    defaults: { _controller: CairnUserBundle:Banking:reconversionRequest, _format: html }
    requirements:
        _format: html|json

cairn_user_banking_conversion_request:
    path:     banking/conversion/request.{_format}
    defaults: { _controller: CairnUserBundle:Banking:conversionRequest, _format: html }
    requirements:
        _format: html|json

cairn_user_banking_operation_confirm:
    path:     banking/operation/confirm/{type}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:confirmOperation, _format: html }
    requirements:
        type: transaction|conversion|reconversion|deposit|withdrawal
        _format: html|json


cairn_user_banking_transaction_scheduled_changestatus:
    path:     banking/transaction/scheduled/edit/{id}-{status}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:changeStatusScheduledTransaction, _format: html}
    requirements:
        id: "[-]?[0-9]{1,}"
        status: cancel|open|block|execute
        _format: html|json

cairn_user_banking_transaction_recurring_cancel:
    path:     banking/transaction/recurring/cancel/{id}/
    defaults: { _controller: CairnUserBundle:Banking:cancelRecurringTransaction }
    requirements:
        id: "[-]?[0-9]{1,}"


cairn_user_banking_account_operations:
    path:     banking/account/operations/{accountID}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:accountOperations, _format: html }
    requirements:
        id: "[-]?[0-9]{1,}"
        _format: html|json

cairn_user_banking_transactions_recurring_view_detailed:
    path:     banking/transactions/recurring/view/detailed/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:viewDetailedRecurringTransaction, _format: html }
    requirements:
        id: "[-]?[0-9]{1,}"
        _format: html|json

cairn_user_banking_transfer_view:
    path:     banking/transfer/view/{type}-{id}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:viewTransfer, _format: html }
    requirements:
        type: scheduled.past|scheduled.futur|recurring|simple
        _format: html|json

cairn_user_banking_transaction_occurrence_execute:
    path:     banking/transactions/recurring/occurrence/execute/{id}/
    defaults: { _controller: CairnUserBundle:Banking:executeOccurrence }
    requirements:
        id: "[-]?[0-9]{1,}"

cairn_user_banking_accounts_overview:
    path:     banking/accounts/overview/{id}.{_format}
    defaults: { _controller: CairnUserBundle:Banking:accountsOverview, _format: html  }
    requirements:
        id: \d+
        _format: html|json


#cairn_user_bankconnection_deposit_index:
#    path:     deposit/index
#    defaults: { _controller: CairnUserBundle:BankConnection:index }
#
#cairn_user_bankconnection_envelope_new:
#    path:     envelope/new
#    defaults: { _controller: CairnUserBundle:BankConnection:newEnvelope }
#
#cairn_user_bankconnection_deposit_new:
#    path:     deposit/new
#    defaults: { _controller: CairnUserBundle:BankConnection:newDeposit }
#
#cairn_user_bankconnection_deposit_confirm:
#    path:     deposit/confirm
#    defaults: { _controller: CairnUserBundle:BankConnection:confirmDeposit }
#
#cairn_user_bankconnection_deposit_view:
#    path:     deposit/view/{id}
#    defaults: { _controller: CairnUserBundle:BankConnection:viewDeposit }
#
#cairn_user_bankconnection_deposit_edit:
#    path:     deposit/edit/{id}
#    defaults: { _controller: CairnUserBundle:BankConnection:editDeposit }
#
#cairn_user_bankconnection_withdrawal_index:
#    path:     withdrawal/index
#    defaults: { _controller: CairnUserBundle:BankConnection:index }
#
#cairn_user_bankconnection_withdrawal_new:
#    path:     withdrawal/new
#    defaults: { _controller: CairnUserBundle:BankConnection:newWithdrawal }
#
#cairn_user_bankconnection_withdrawal_confirm:
#    path:     withdrawal/confirm
#    defaults: { _controller: CairnUserBundle:BankConnection:confirmWithdrawal }
#
#cairn_user_bankconnection_withdrawal_view:
#    path:     withdrawal/view/{id}
#    defaults: { _controller: CairnUserBundle:BankConnection:viewWithdrawal }
#
#cairn_user_bankconnection_withdrawal_edit:
#    path:     withdrawal/edit/{id}
#    defaults: { _controller: CairnUserBundle:BankConnection:editWithdrawal }
#
#cairn_user_banknotes_home:
#    path:     banknote/home
#    defaults: { _controller: CairnUserBundle:Banknote:index }
#
#cairn_user_multiform:
#    path:    banknote/test
#    defaults: { _controller: CairnUserBundle:Banknote:multiform }
#
#cairn_user_banknote_add:
#    path:     /banknote/add
#    defaults: { _controller: CairnUserBundle:Banknote:addBanknote }
#
#cairn_user_banknote_edit:
#    path:     /banknote/edit/{id}
#    defaults: { _controller: CairnUserBundle:Banknote:editBanknote }
#
#cairn_user_banknote_view:
#    path:     /banknote/view/{id}
#    defaults: { _controller: CairnUserBundle:Banknote:viewBanknote }
#
#cairn_user_banknote_search:
#    path:     /banknote/search
#    defaults: { _controller: CairnUserBundle:Banknote:searchBanknotes }
#
#cairn_user_banknote_remove:
#    path:     /banknote/remove/{id}
#    defaults: { _controller: CairnUserBundle:Banknote:removeBanknote }
#
