services:

    Cairn\UserBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    cairn_user.repository_sms:
        class: SmsRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\Sms]

    cairn_user.repository_user: 
        class: UserRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\User]

    cairn_user.repository_operation: 
        class: OperationRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\Operation]

    cairn_user.repository_smsdata: 
        class: SmsDataRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\SmsData]

    cairn_user.repository_phone: 
        class: PhoneRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\Phone]

    cairn_user.repository_card: 
        class: CardRepository
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\Card]

    cairn_user.api:
        public: true
        class: Cairn\UserBundle\Service\Api
        arguments:
            - "@request_stack"

    cairn_user.api_authenticator:
        public: true
        class: Cairn\UserBundle\Security\TokenAuthenticator
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.security"

    cairn_user.commands:
        class: Cairn\UserBundle\Service\Commands
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@cairn_user.message_notificator"
            - "@templating"
            - "%card_association_delay%"
            - "%cairn_email_activation_delay%"
            - "@router"
            - "@service_container"

    cairn_user.counter:
        class: Cairn\UserBundle\Service\Counter

    cairn_user.helloasso:
        class: Cairn\UserBundle\Service\Helloasso
        arguments:
            - "%helloasso_api_login%"
            - "%helloasso_api_password%"

    cairn_user.message_notificator:
        class: Cairn\UserBundle\Service\MessageNotificator
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.repository_sms"
            - "@mailer" 
            - "@templating"
            - "%cairn_email_technical_services%"
            - "%cairn_email_noreply%"
            - "%kernel.environment%"
            - "%notificator_consts%"

    cairn_user.bridge_symfony:
        class: Cairn\UserBundle\Service\BridgeToSymfony
        arguments:
            - "@cairn_user.message_notificator"
            - "@cairn_user.repository_user"
            - "@cairn_user_cyclos_user_info"
            - "@cairn_user.repository_operation"
            - "@cairn_user_cyclos_banking_info"

    cairn_user.access_platform:
        class: Cairn\UserBundle\Service\AccessPlatform
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.message_notificator"
            - "@cairn_user.security"
            - "@cairn_user_cyclos_network_info"
            - "%cyclos_anonymous_user%"
            - "%cyclos_currency_cairn%"

    cairn_user.datetime_checker:
        class: Cairn\UserBundle\Service\DateTimeChecker

    cairn_user.security:
        public: true
        class: Cairn\UserBundle\Service\Security
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.repository_operation"
            - "@cairn_user.repository_card"
            - "@security.token_storage"
            - "@security.encoder_factory" 
            - "@cairn_user_cyclos_useridentification_info"
            - "%secret%" 
            - "%sms_daily_thresholds%" 

    cairn_user.operation_listener:
        class: Cairn\UserBundle\EventListener\OperationListener
        arguments:
            - "@cairn_user_cyclos_banking_info"
            - "@cairn_user.bridge_symfony"
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, method: postLoad, entity: Cairn\UserBundle\Entity\Operation, lazy: true }

    cairn_user.registration_listener:
        class: Cairn\UserBundle\EventListener\RegistrationListener
        arguments: 
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize, method: onRegistrationInitialize }
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistrationSuccess, priority: -512 }
            - { name: kernel.event_listener, event: fos_user.registration.confirm, method: onRegistrationConfirm }
            - { name: kernel.event_listener, event: fos_user.profile.edit.success, method: onProfileEditSuccess, priority: -512 }

    cairn_user.security.input_listener:
        class: Cairn\UserBundle\EventListener\SecurityListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onMaintenance, priority: 1024 }
            - { name: kernel.event_listener, event: kernel.request, method: onFirstLogin, priority: -1024 }
            - { name: kernel.event_listener, event: kernel.response, method: onDisabledUser, priority: 128 }
            - { name: kernel.event_listener, event: kernel.request, method: onSensibleOperations }
            - { name: kernel.event_listener, event: cairn_user.input_card_key, method: onCardKeyInput }
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin, priority: 128 }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
#            - { name: kernel.event_listener, event: fos_user.resetting.send_email.initialize, method: onResetPasswordInit }
            - { name: kernel.event_listener, event: fos_user.resetting.reset.success, method: onResetPasswordSubmit }
            - { name: kernel.event_listener, event: fos_user.change_password.edit.success, method: onChangePassword }


    cairn_user.technical.exception_listener:
        class: Cairn\UserBundle\EventListener\ExceptionListener
        arguments:
            - "@cairn_user.message_notificator"
            - "@cairn_user.access_platform"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@cairn_user.security"
        tags:  
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
    
    cairn_user.user_validator:
        class: Cairn\UserBundle\Validator\UserValidator
        arguments:
            - "%cyclos_currency_cairn%"
            - "%cyclos_group_pros%"
            - "@cairn_user_cyclos_channel_info"
            - "@cairn_user_cyclos_group_info"
            - "@cairn_user_cyclos_network_info"
            - "@cairn_user.repository_user"
        tags:
            - { name: validator.constraint_validator, alias: cairn_user_validator }

    cairn_user.user_password_validator:
        class: Cairn\UserBundle\Validator\UserPasswordValidator
        arguments:
            - "@security.encoder_factory" 
            - "@cairn_user.counter"
            - "@cairn_user.access_platform"
            - "@doctrine.orm.entity_manager"
            - "@cairn_user.security"
        tags:
            - { name: validator.constraint_validator, alias: cairn_user_password_validator }

    cairn_user.user_phone_number_validator:
        class: Cairn\UserBundle\Validator\UserPhoneNumberValidator
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.security"
        tags:
            - { name: validator.constraint_validator, alias: cairn_user_phone_number_validator }


    cairn_user.operation_validator:
        class: Cairn\UserBundle\Validator\OperationValidator
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user_cyclos_user_info"
            - "@cairn_user_cyclos_account_info"
        tags:
            - { name: validator.constraint_validator, alias: cairn_operation_validator }

    cairn_user.mandate_validator:
        class: Cairn\UserBundle\Validator\MandateValidator
        arguments:
            - "@cairn_user.repository_mandate"
        tags:
            - { name: validator.constraint_validator, alias: cairn_mandate_validator }

    Cairn\UserBundle\Form\Extension\DisableCSRFExtension:
        arguments:
            - "@cairn_user.api"
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType}

    cairn_user.zipcity_to_sting_transformer:
        class: Cairn\UserBundle\Form\DataTransformer\ZipCityToStringTransformer
        arguments: ["@doctrine.orm.entity_manager"]

    cairn_user.account_to_sting_transformer:
        class: Cairn\UserBundle\Form\DataTransformer\AccountToStringTransformer
        arguments: ["@doctrine.orm.entity_manager","@cairn_user.bridge_symfony","@cairn_user_cyclos_user_info","@cairn_user_cyclos_account_info"]

    Cairn\UserBundle\Form\ProfileType:
        arguments: ['@security.authorization_checker']
        tags: [form.type]

    Cairn\UserBundle\Form\PhoneType:
        arguments: ['@security.authorization_checker','@request_stack','@cairn_user.repository_phone']
        tags: [form.type]

    Cairn\UserBundle\Form\ChangePasswordType:
        arguments: ['@security.password_encoder']
        tags: [form.type]

    Cairn\UserBundle\Form\CreditType:
        arguments: ['@security.authorization_checker']
        tags: [form.type]

    Cairn\UserBundle\Form\WithdrawalType:                              
        arguments: ['@security.token_storage']                                 
        tags: [form.type]

    Cairn\UserBundle\Form\DepositType:                              
        arguments: ['@security.token_storage']                                 
        tags: [form.type]


    Cairn\UserBundle\Form\OperationType:
        arguments: ['@security.token_storage','@validator',"@cairn_user_cyclos_account_info","@cairn_user.bridge_symfony"]
        tags: [form.type]

    Cairn\UserBundle\Form\RegistrationType:
        arguments: ['@security.authorization_checker',"@doctrine.orm.entity_manager"]
        tags: [form.type]

    Cairn\UserBundle\Form\ZipCitySelectorType:
        arguments: ["@cairn_user.zipcity_to_sting_transformer"]
        tags: [form.type]

    Cairn\UserBundle\Form\AccountType:
        arguments: ["@cairn_user.account_to_sting_transformer"]
        tags: [form.type]
