services:
    #    cairn_user.example:
    #        class: Cairn\UserBundle\Example
    #        arguments: ["@service_id", "plain_value", "%parameter%"]

    cairn_user.repository_user: 
        class: UserRepository                                                  
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\User] 

    cairn_user.repository_operation: 
        class: OperationRepository                                                  
        factory: ["@doctrine.orm.entity_manager", getRepository]
        arguments: [Cairn\UserBundle\Entity\Operation] 

    cairn_user.commands:
        class: Cairn\UserBundle\Service\Commands
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@cairn_user.message_notificator"
            - "@templating"
            - "%card_activation_delay%"
            - "%cairn_email_activation_delay%"
            - "@router"
            - "@service_container"

    cairn_user.counter:
        class: Cairn\UserBundle\Service\Counter

    cairn_user.message_notificator:
        class: Cairn\UserBundle\Service\MessageNotificator
        arguments:
            - "@cairn_user.repository_user"
            - "@mailer" 
            - "%cairn_email_technical_services%"
            - "%cairn_email_noreply%"

    cairn_user.bridge_symfony:
        class: Cairn\UserBundle\Service\BridgeToSymfony
        arguments:
            - "@cairn_user.message_notificator"
            - "@cairn_user.repository_user"
            - "@cairn_user_cyclos_user_info"
            - "@cairn_user.repository_operation"
            - "@cairn_user_cyclos_banking_info"

    cairn_user.access_platform:
        class: Cairn\UserBundle\Service\AccessPlatform
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user.message_notificator"

    cairn_user.datetime_checker:
        class: Cairn\UserBundle\Service\DateTimeChecker

    cairn_user.security:
        class: Cairn\UserBundle\Service\Security
        arguments:
            - "@cairn_user.repository_user"
            - "@security.token_storage"
            - "@security.encoder_factory" 

    cairn_user.operation_listener:
        class: Cairn\UserBundle\EventListener\OperationListener
        arguments:
            - "@cairn_user_cyclos_banking_info"
            - "@cairn_user.bridge_symfony"
        tags:
            - { name: doctrine.orm.entity_listener, event: postLoad, lazy: true }

    cairn_user.registration_listener:
        class: Cairn\UserBundle\EventListener\RegistrationListener
        arguments: 
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: fos_user.registration.initialize, method: onRegistrationInitialize }
            - { name: kernel.event_listener, event: fos_user.registration.success, method: onRegistrationSuccess }
            - { name: kernel.event_listener, event: fos_user.registration.confirm, method: onRegistrationConfirm }
            - { name: kernel.event_listener, event: fos_user.profile.edit.success, method: onProfileEdit }

    cairn_user.security.input_listener:
        class: Cairn\UserBundle\EventListener\SecurityListener
        arguments:
            - "@service_container"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onMaintenance }
            - { name: kernel.event_listener, event: kernel.request, method: onSensibleOperations }
            - { name: kernel.event_listener, event: cairn_user.input_card_key, method: onCardKeyInput }
            - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            - { name: kernel.event_listener, event: fos_user.resetting.send_email.initialize, method: onResetPassword }
            - { name: kernel.event_listener, event: fos_user.change_password.edit.success, method: onChangePassword }


    cairn_user.technical.exception_listener:
        class: Cairn\UserBundle\EventListener\ExceptionListener
        arguments:
            - "@cairn_user.message_notificator"
            - "@cairn_user.access_platform"
            - "@doctrine.orm.entity_manager"
            - "@router"
            - "@cairn_user.security"
        tags:  
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException}
    
    cairn_user.user_validator:
        class: Cairn\UserBundle\Validator\UserValidator
        arguments:
            - "%cyclos_network_cairn%"
            - "%cyclos_group_pros%"
            - "@cairn_user_cyclos_channel_info"
            - "@cairn_user_cyclos_group_info"
            - "@cairn_user_cyclos_network_info"
        tags:
            - { name: validator.constraint_validator, alias: cairn_user_validator }

    cairn_user.user_password_validator:
        class: Cairn\UserBundle\Validator\UserPasswordValidator
        arguments:
            - "@security.encoder_factory" 
            - "@cairn_user.counter"
            - "@cairn_user.access_platform"
            - "@doctrine.orm.entity_manager"
            - "@cairn_user.security"
        tags:
            - { name: validator.constraint_validator, alias: cairn_user_password_validator }

    cairn_user.operation_validator:
        class: Cairn\UserBundle\Validator\OperationValidator
        arguments:
            - "@cairn_user.repository_user"
            - "@cairn_user_cyclos_user_info"
            - "@cairn_user_cyclos_account_info"
        tags:
            - { name: validator.constraint_validator, alias: cairn_operation_validator }

    Cairn\UserBundle\Form\CreditType:
        arguments: ['@security.authorization_checker']
        tags: [form.type]

    Cairn\UserBundle\Form\WithdrawalType:                              
        arguments: ['@security.token_storage']                                 
        tags: [form.type]

    Cairn\UserBundle\Form\DepositType:                              
        arguments: ['@security.token_storage']                                 
        tags: [form.type]
