# src/Cairn/UserBundle/Resources/config/validation.yml

Cairn\UserBundle\Entity\User:
    constraints:
            - Cairn\UserBundle\Validator\User: ~

Cairn\UserBundle\Entity\Operation:
    constraints:
            - Cairn\UserBundle\Validator\Operation: ~

Cairn\UserBundle\Entity\SmsData:
    constraints:
            - Cairn\UserBundle\Validator\SmsData: ~


FOS\UserBundle\Model\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: email
        errorPath: email
        message: fos_user.email.already_used
        groups: [ "CairnRegistration", "CairnProfile" ]

  properties:
    email:
      - NotBlank:
          message: fos_user.email.blank
          groups: [ "CairnRegistration", "CairnProfile" ]
      - Length:
          min: 2
          minMessage: fos_user.email.short
          max: 255
          maxMessage: fos_user.email.long
          groups: [ "CairnRegistration", "ResetPassword" ]
      - Email:
          message: fos_user.email.invalid
          groups: [ "CairnRegistration", "CairnProfile" ]

FOS\UserBundle\Model\Group:
  properties:
    name:
      - NotBlank:
          message: fos_user.group.blank
          groups: [ "CairnRegistration" ]
      - Length:
          min: 2
          minMessage: fos_user.group.short
          max: 255
          maxMessage: fos_user.group.long
          groups: [ "CairnRegistration" ]

FOS\UserBundle\Propel\User:
  properties:
    email:
      - NotBlank:
          message: fos_user.email.blank
          groups: [ "CairnRegistration", "CairnProfile" ]
      - Length:
          min: 2
          minMessage: fos_user.email.short
          max: 255
          maxMessage: fos_user.email.long
          groups: [ "CairnRegistration", "ResetPassword" ]
      - Email:
          message: fos_user.email.invalid
          groups: [ "CairnRegistration", "CairnProfile" ]

    plainPassword:
      - NotBlank:
          message: fos_user.password.blank
          groups: [ "CairnRegistration", "ResetPassword", "ChangePassword" ]
      - Length:
          min: 2
          max: 4096
          minMessage: fos_user.password.short
          groups: [ "CairnRegistration", "CairnProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
  properties:
    name:
      - NotBlank:
          message: fos_user.group.blank
          groups: [ "CairnRegistration" ]
      - Length:
          min: 2
          minMessage: fos_user.group.short
          max: 255
          maxMessage: fos_user.group.long
          groups: [ "CairnRegistration" ]