# src/Cairn/UserBundle/Resources/config/validation.yml

Cairn\UserBundle\Entity\User:
    constraints:
            - Cairn\UserBundle\Validator\User: ~

Cairn\UserBundle\Entity\Operation:
    constraints:
            - Cairn\UserBundle\Validator\Operation: ~

